### ISSUE TITLE
Doesn't render in Istanbul

### ISSUE THREAD

**Issue by cburkins** [service-portal/CCW3955#1]
First of all, thanks for contributing this to the community.  

Anxious to try this out; however, I'm thinking it might only run in Jakarta.  So I've got two ideas:  Can you enhance the code so it works on Istanbul ?  Or perhaps give me access to Jakarta?     I'll assume the former :)

Repo loads fine into Istanbul Studio.   When I load the /d1 page, I get the following error: "Function addTrend is not allowed in scope x_snc_dashboard"

![image](https://cloud.githubusercontent.com/assets/9342308/25872547/3223ec1c-34d9-11e7-9e59-6ea46fe39474.png)

**Comment by iamwill** [comment]
Thanks for reporting! I am working on it. Expect a fix soon.

**Comment by cburkins** [comment]
Thanks Will.  No rush.  I'm sure you've got a busy week.  We can all wait until next week, I'm sure :)

**Comment by mattifh** [comment]
I would love to get a working version for Istanbul as well. Of course, there is no rush!

**Comment by BobBeck95** [comment]
Will, do you have an ETA for when this will be available?  No rush, but wanted to get an idea as to when

**Comment by iamwill** [comment]
Today

**Comment by cburkins** [comment]
You're a generous man, Will.

**Comment by BobBeck95** [comment]
Was the Istanbul code put out yesterday?

**Comment by iamwill** [comment]
Sadly I wasn't able to finish it. This has actually turned out to be really difficult. I'm working on it right now.

Time interval needs to support the following choices:
Year
Quarter
Date
Week
DayOfWeek
Hour
Value

I'm focusing on Month first and then I will figure out the others.

As soon as I have something working I'll push the code and tell everyone here.

Sorry for the delay.
Will

**Comment by BobBeck95** [comment]
No worries.  Thanks for the update.

**Comment by BobBeck95** [comment]
Will, has there been any updates to this?  I would not ask, but we are validated and not able to move to Jakarta until 2018.

**Comment by iamwill** [comment]
Not yet - I spent some time working on that API but I haven't finished it. I don't know when I will get back to it.

Anyone want to take a stab at it?
